### ISSUE TITLE
Solver runs but figure shows up blank?

### ISSUE THREAD

**Issue by wgosrich** [snarayan21/task-graphs#2]
https://github.com/snarayan21/task-graphs/blob/38c51f8b71220ed630f7d1b9f24d63474253eed8/modular-code/taskgraph.py#L265

I was getting some errors related to the latex before --- I installed the following things and now latex seems fine:
sudo apt install texlive-fonts-recommended texlive-fonts-extra
sudo apt install dvipng
sudo apt install cm-super

When I run for only one iteration, it shows me the figure totally fine. When it's run in a loop, it just shows up blank until the very last frame - no animation or anything.

**Comment by siddharth119** [comment]
That is strange... can you post the result for
 >>> import matplotlib
>>> matplotlib.get_backend()

**Comment by wgosrich** [comment]
> That is strange... can you post the result for
> 
> > > > import matplotlib
> > > > matplotlib.get_backend()

'Qt5Agg'

**Comment by siddharth119** [comment]
can you put matplotlib.use('TKAgg',warn=False, force=True) at the beginning of your code and try

**Comment by wgosrich** [comment]
That worked!! I had to delete the "warn=False" because it threw an error, but that worked!

**Comment by siddharth119** [comment]
nice!!
